### ISSUE TITLE
Rationale behind the static allocation of 256 profiles

### ISSUE THREAD

**Issue by iomz** [Interactions-HSG/uArm-Controller#14]
We discussed this several times in the past, but I cannot remember precisely why we'd rather preallocate 256 profiles and iterate all of them in the main loop, rather than dynamically allocating memory for each profile upon registration and maintaining a single linked list of the profiles.

I think at the moment both memory footprint and overhead of accessing 256 `profile_manager.events` are enormous, but I guess this came from something related to delegating the profile ID management to the "gateway" and to saving memory space for storing the ID...?

**Comment by iomz** [comment]
As a memorandum I'm answering this to myself; it has the static allocation because
- the index number is used for the profile management in Gateway
- the index numbers are also coupled with the state of interactions flags; waiting/blocking/deactivated -> the definition of these is necessary in addition to the profile management state machine.
- due to the flag checking mechanism, the memory footprints don't exceed as it would by preallocating an empty profile array -> vs. Linked List?

@jo-bru Is it correct?

**Comment by jo-bru** [comment]
Exactly, the profile index (`profile_id`) is used on the controller-level as a unique identifier for all profiles/devices. The profile index to GIAI/UUID mapping will be done in the gateway.
The reasons for using a statically allocated array to store the profiles on the controller are:
- The profile lookup gets much simpler and faster, as the profile_id corresponds to the index of the array.
Therefore, we can directly get the corresponding profile instead of searching the profile by iterating over all elements.
- If we strictly use less than 256 profiles per controller we don't have to care for memory overflow, as the space for all profiles gets preallocated.

As for now, we use about 60% of the available RAM, if the available space gets too small in the future, we can decrease the maximum number of profiles (now 256, which is IMO far too much). 
We may want to extend this in a future version to be able to dynamically change the maximum number of profiles with a request.

**Comment by iomz** [comment]
Thank you!
